hpc <- read.table(file = "household_power_consumption.txt", header = TRUE, sep = ";", dec = ".", na.strings = "?")
hpc$Date <- as.Date(as.character(hpc$Date), format="%d/%m/%Y")
sel <- subset(hpc, Date == "2007-02-01" | Date == "2007-02-02")
sel$datetime <- strptime(paste(sel$Date,sel$Time), format="%Y-%m-%d %H:%M:%S")

png(filename = "plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
plot(sel$datetime, sel$Global_active_power, type="l", xlab = "", ylab = "Global Active Power", main = "")
plot(sel$datetime, sel$Voltage, type="l", xlab = "datetime", ylab = "Voltage", main = "")
plot(sel$datetime, sel$Sub_metering_1, type="l", col = "Black", xlab = "", ylab = "Energy sub metering")
lines(sel$datetime, sel$Sub_metering_2, type="l", col = "Red")
lines(sel$datetime, sel$Sub_metering_3, type="l", col = "Blue")
legend("topright", bty = "n", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty=c(1,1,1), col=c("Black","Red","Blue"), cex=0.8)
plot(sel$datetime, sel$Global_reactive_power, type="l", xlab = "datetime", ylab = "Global_reactive_power")
dev.off()
